warriors: 
  nickname: "your-username"
  projects: 
  - name: us-government
    replicas: 1

dashboard: 
  image:
    repository: "jordanbmoore/atw-dashboard"
    tag: "latest"
  httproute:
    enabled: false