warriors: 
  nickname: "your-username"
  projects: 
  - name: usgovernment
    replicas: 1

dashboard: 
  image:
    repository: "jordanbmoore/atw-dashboard"
    tag: "latest"
  service: 
    annotations: {}
  httproute:
    enabled: false