apiVersion: v1
kind: ConfigMap
metadata:
  name: atw-dashboard
  labels:
    app.kubernetes.io/name: atw-dashboard
data:
  config.yaml: |
    listen_addr: ":8080"
    nickname: "your-nickname"
    leaderboard_interval: 5m
    warriors:
      - name: warrior-1
        url: http://warrior-1.warriors.svc.cluster.local:8001
      - name: warrior-2
        url: http://warrior-2.warriors.svc.cluster.local:8001
