listen_addr: ":8080"
nickname: "your-nickname"

# leaderboard_interval: 5m
# reconnect_min: 1s
# reconnect_max: 60s

warriors:
  - name: warrior-0
    url: http://warrior-0:8001
  - name: warrior-1
    url: http://warrior-1:8001
