listen_addr: ":8080"
nickname: "your-nickname"

# leaderboard_interval: 5m
# reconnect_min: 1s
# reconnect_max: 60s

warriors:
  - name: telegram-1
    url: http://atw-telegram-1:8001
  - name: telegram-2
    url: http://atw-telegram-2:8001
  - name: usgovernment-1
    url: http://atw-usgovernment-1:8001
  - name: usgovernment-2
    url: http://atw-usgovernment-2:8001
