services:
  atw-dashboard:
    image: jordanbmoore/atw-dashboard
    ports:
    - "8080:8080"
    volumes:
    - ./config.yaml:/etc/atw-dashboard/config.yaml:ro
    restart: unless-stopped
  warrior-0:
    labels:
        - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    environment:
      - SELECTED_PROJECT=usgovernment
      - WARRIOR_ID=
      - DOWNLOADER=
      - CONCURRENT_ITEMS=
  warrior-1:
    labels:
        - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    environment:
      - SELECTED_PROJECT=usgovernment
      - WARRIOR_ID=
      - DOWNLOADER=
      - CONCURRENT_ITEMS=
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    image: nickfedor/watchtower
    command: --label-enable --cleanup --include-restarting --interval 3600