name: atw
services:
  atw-dashboard:
    image: jordanbmoore/atw-dashboard
    ports:
    - "8080:8080"
    volumes:
    - ./config.yaml:/etc/atw-dashboard/config.yaml:ro
    restart: unless-stopped
    networks:
      - atw
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    image: nickfedor/watchtower
    command: --label-enable --cleanup --include-restarting --interval 3600
  telegram:
    labels:
        - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    environment:
      - SELECTED_PROJECT=telegram
      - DOWNLOADER=your-nickname
      - CONCURRENT_ITEMS=
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - atw
  usgovernment:
    labels:
        - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    environment:
      - SELECTED_PROJECT=usgovernment
      - DOWNLOADER=your-nickname
      - CONCURRENT_ITEMS=
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - atw
networks:
  atw: {}